### ISSUE TITLE
Plugins doesn't load properly with lastest Kate and Pate

### ISSUE THREAD

**Issue by ablanco** [goinnn/Kate-plugins#12]
Hi. When I launch Kate with the plugins activated, then an error happens:

```
$ kate
QDBusConnection: session D-Bus connection created before QCoreApplication. Application may misbehave.
kate(10375)/kdecore (KLibrary) kde4Factory: The library "/usr/lib/kde4/pateplugin.so" does not offer a qt_plugin_instance function.
kate(10375)/Kate (Plugins): "Traceback (most recent call last):
  File "/usr/share/apps/kate/pate/kate_plugins/kate_plugins.py", line 17, in <module>
    from jste_plugins.autocomplete import *
  File "/usr/share/apps/kate/pate/kate_plugins/jste_plugins/autocomplete.py", line 23, in <module>
    from kate_settings_plugins import (JAVASCRIPT_AUTOCOMPLETE_ENABLED,
  File "/usr/share/apps/kate/pate/kate_plugins/kate_settings_plugins.py", line 19, in <module>
    PY_MENU = create_mainmenu('Python', 'python')
  File "/usr/share/apps/kate/pate/kate_plugins/kate_core_plugins.py", line 122, in create_mainmenu
    window = kate.mainWindow()
  File "/usr/share/apps/kate/plugins/pate/kate/__init__.py", line 366, in mainWindow
    return application.activeMainWindow().window()
'NoneType' object has no attribute 'window'
Could not import kate_plugins"
```

Kate version: 3.9.2
KDE version: 4.9.2
Pate version: Lastest from git://anongit.kde.org/kate installed through [this package](https://aur.archlinux.org/packages.php?ID=27199)

After loading Kate, and seeing the trace on the terminal, I go to the settings and reload the plugins. This time the plugins load properly and no exception in throwed, but its menus are empty. There are screenshots of these steps here: http://imgur.com/a/TRWiA One just after launching Kate, one after realoading the plugins, and the last one is of the empty menus.

It seems that the first crash is due to Pate loading the plugins before Kate is ready, and therefore no application object exists. But if I reload the plugins after Kate is fully loaded they don't work either, nor by the menus nor when saving.

Regards.

**Comment by mborho** [comment]
Same here. Build it on Kubuntu 12.04.

**Comment by goinnn** [comment]
Grrrr I have to update my OS.... and update something of this plugin... 

Thanks for the report

**Comment by goinnn** [comment]
Now works in Kubuntu 12.10 with the last Kate 8Building Kate from Sources):

http://kate-editor.org/get-it/
